spring.application.name=order-logistics-agent-server

spring.config.import=nacos:order-logistics-agent-server.properties?group=ORDER_LOGISTICS_AGENT&refreshEnabled=false

spring.cloud.nacos.server-addr=${NACOS_SERVER_ADDR:127.0.0.1:8848}
spring.cloud.nacos.config.namespace=${NACOS_NAMESPACE:order-logistics-agent-dev}
spring.cloud.nacos.username=${NACOS_USERNAME}
spring.cloud.nacos.password=${NACOS_PASSWORD}
