package com.xjjk.agent.memory.domain;

/** 不包含用户或模型正文的隐式记忆抽取完成结果。 */
public enum MemoryExtractionResultCode {
    SAVED,
    IGNORE,
    SESSION_ONLY,
    MODEL_EMPTY,
    ALL_REJECTED,
    REJECTED_SCHEMA,
    REJECTED_EVIDENCE,
    REJECTED_SENSITIVE,
    REJECTED_STABILITY,
    REJECTED_CONFIDENCE,
    REJECTED_UNSUPPORTED,
    REJECTED_CONTRADICTED,
    REJECTED_UNCERTAIN,
    NO_CHANGE,
    MODEL_PROTOCOL_REJECTED
}
